function [Aa, Ab, As] = matrices_A_12f3(param,hx)
% Mathematica, materials12f3.nb
% 8 jan 2020
% A-matrices for il-model.
bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
nx= size(hx,1); % need to figure this out later

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% The only thing you need to specify by hand is 
ia = (eye(nx)-alph*bet*hx)^(-1);
ib = (eye(nx)-bet*hx)^(-1);

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [((-1)+alph).*bet.*((-1)+bet.*rho+(-1).*psix.*sig).*(1+(-1).*bet.* ...
  rho+kapp.*psipi.*sig+psix.*sig).^(-1),alph.*bet.*kapp.*((-1)+bet.* ...
  rho+(-1).*psix.*sig).*((-1)+bet.*rho+(-1).*(kapp.*psipi+psix).* ...
  sig).^(-1),0;(-1).*((-1)+alph).*bet.*psipi.*sig.*((-1)+bet.*rho+( ...
  -1).*(kapp.*psipi+psix).*sig).^(-1),alph.*bet.*kapp.*psipi.*sig.*( ...
  (-1)+bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1),0;((-1)+alph).* ...
  bet.*psipi.*((-1)+bet.*rho).*(1+(-1).*bet.*rho+kapp.*psipi.*sig+ ...
  psix.*sig).^(-1),alph.*bet.*kapp.*psipi.*((-1)+bet.*rho).*((-1)+ ...
  bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1),0];
Ab = [(-1).*kapp.*((-1)+bet.*(psipi+rho)).*sig.*(1+(-1).*bet.*rho+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1),kapp.*(1+(-1).*bet.*rho+kapp.* ...
  psipi.*sig+psix.*sig).^(-1).*(1+bet.^2.*rho+(-1).*bet.*(1+rho+ ...
  psix.*sig)),0;(1+(-1).*bet.*rho+kapp.*psipi.*sig+psix.*sig).^(-1) ...
  .*(sig+(-1).*bet.*(psipi+rho).*sig),((-1)+bet.*rho+(-1).*(kapp.* ...
  psipi+psix).*sig).^(-1).*((-1)+bet.*(1+rho+(-1).*bet.*rho+psix.* ...
  sig)),0;(-1).*(kapp.*psipi+psix).*((-1)+bet.*(psipi+rho)).*sig.*( ...
  1+(-1).*bet.*rho+kapp.*psipi.*sig+psix.*sig).^(-1),(kapp.*psipi+ ...
  psix).*((-1)+bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1).*((-1)+ ...
  bet.*(1+rho+(-1).*bet.*rho+psix.*sig)),0];
As = [((-1)+bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1).*(((-1)+bet.* ...
  rho+(-1).*psix.*sig).*ia(3,1)+kapp.*sig.*(((-1)+bet.*rho).*ib(1,1) ...
  +ib(2,1))),((-1)+bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1).*(( ...
  (-1)+bet.*rho+(-1).*psix.*sig).*ia(3,2)+kapp.*sig.*(((-1)+bet.* ...
  rho).*ib(1,2)+ib(2,2))),((-1)+bet.*rho+(-1).*(kapp.*psipi+psix).* ...
  sig).^(-1).*(((-1)+bet.*rho+(-1).*psix.*sig).*ia(3,3)+kapp.*sig.*( ...
  ((-1)+bet.*rho).*ib(1,3)+ib(2,3))),((-1)+bet.*rho+(-1).*(kapp.* ...
  psipi+psix).*sig).^(-1).*(((-1)+bet.*rho+(-1).*psix.*sig).*ia(3,4) ...
  +kapp.*sig.*(rho+(-1).*ib(1,4)+bet.*rho.*ib(1,4)+ib(2,4)));(-1).* ...
  sig.*(1+(-1).*bet.*rho+kapp.*psipi.*sig+psix.*sig).^(-1).*(psipi.* ...
  ia(3,1)+((-1)+bet.*rho).*ib(1,1)+ib(2,1)),(-1).*sig.*(1+(-1).* ...
  bet.*rho+kapp.*psipi.*sig+psix.*sig).^(-1).*(psipi.*ia(3,2)+((-1)+ ...
  bet.*rho).*ib(1,2)+ib(2,2)),(-1).*sig.*(1+(-1).*bet.*rho+kapp.* ...
  psipi.*sig+psix.*sig).^(-1).*(psipi.*ia(3,3)+((-1)+bet.*rho).*ib( ...
  1,3)+ib(2,3)),(-1).*sig.*(1+(-1).*bet.*rho+kapp.*psipi.*sig+psix.* ...
  sig).^(-1).*(rho+psipi.*ia(3,4)+(-1).*ib(1,4)+bet.*rho.*ib(1,4)+ ...
  ib(2,4));((-1)+bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1).*((( ...
  -1)+bet.*rho).*(psipi.*ia(3,1)+(kapp.*psipi+psix).*sig.*ib(1,1))+( ...
  kapp.*psipi+psix).*sig.*ib(2,1)),((-1)+bet.*rho+(-1).*(kapp.* ...
  psipi+psix).*sig).^(-1).*((-1)+bet.*rho.*(1+psipi.*ia(3,2)+(kapp.* ...
  psipi+psix).*sig.*ib(1,2))+(-1).*psipi.*(ia(3,2)+kapp.*sig.*(1+ib( ...
  1,2)+(-1).*ib(2,2)))+psix.*sig.*((-1)+(-1).*ib(1,2)+ib(2,2))),(( ...
  -1)+bet.*rho+(-1).*(kapp.*psipi+psix).*sig).^(-1).*(((-1)+bet.* ...
  rho).*(psipi.*ia(3,3)+(kapp.*psipi+psix).*sig.*ib(1,3))+(kapp.* ...
  psipi+psix).*sig.*ib(2,3)),((-1)+bet.*rho+(-1).*(kapp.*psipi+psix) ...
  .*sig).^(-1).*(((-1)+bet.*rho).*(rho+psipi.*ia(3,4)+(kapp.*psipi+ ...
  psix).*sig.*ib(1,4))+(kapp.*psipi+psix).*sig.*ib(2,4))];