function [Aa, Ab, As] = matrices_A_13indexation_myopic(param,hx)
% Mathematica, materials13indexation_myopic.nb
% 17 jan 2020
% A-matrices for baseline model w/ indexation in NKPC, myopic info ass.

bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
gam = param.gam;
nx= size(hx,1); 

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% The only thing you need to specify by hand is 
ia = (eye(nx)-alph*bet*hx)^(-1);
ib = (eye(nx)-bet*hx)^(-1);

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [((-1)+alph).*bet.*(1+kapp.*psipi.*sig+(-1).*psix.*sig).^(-1).*(( ...
  -1)+psix.*sig),alph.*bet.*kapp.*((-1)+psix.*sig).*((-1)+(-1).* ...
  kapp.*psipi.*sig+psix.*sig).^(-1),0;((-1)+alph).*bet.*psipi.*sig.* ...
  (1+kapp.*psipi.*sig+(-1).*psix.*sig).^(-1),alph.*bet.*kapp.* ...
  psipi.*sig.*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1),0;(-1).* ...
  ((-1)+alph).*bet.*psipi.*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig) ...
  .^(-1).*((-1)+2.*psix.*sig),alph.*bet.*kapp.*psipi.*(1+(-2).* ...
  psix.*sig).*(1+kapp.*psipi.*sig+(-1).*psix.*sig).^(-1),0];
Ab = [kapp.*((-1)+bet.*psipi).*sig.*((-1)+(-1).*kapp.*psipi.*sig+psix.* ...
  sig).^(-1),kapp.*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*(( ...
  -1)+bet+bet.*psix.*sig),0;(sig+(-1).*bet.*psipi.*sig).*(1+kapp.* ...
  psipi.*sig+(-1).*psix.*sig).^(-1),((-1)+(-1).*kapp.*psipi.*sig+ ...
  psix.*sig).^(-1).*((-1)+bet+bet.*psix.*sig),0;((-1)+bet.*psipi).*( ...
  kapp.*psipi+psix).*sig.*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^( ...
  -1),(kapp.*psipi+psix).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^( ...
  -1).*((-1)+bet+bet.*psix.*sig),0];
As = [alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*(gam.* ...
  (1+(-1).*psix.*sig).*ia(4,1)+alph.*(((-1)+psix.*sig).*ia(3,1)+ ...
  gam.*((-1)+psix.*sig).*ia(4,1)+kapp.*sig.*((-1).*ib(1,1)+ib(2,1))) ...
  ),alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  gam.*(1+(-1).*psix.*sig).*ia(4,2)+alph.*(((-1)+psix.*sig).*ia(3,2) ...
  +gam.*((-1)+psix.*sig).*ia(4,2)+kapp.*sig.*((-1).*ib(1,2)+ib(2,2)) ...
  )),alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  gam.*(1+(-1).*psix.*sig).*ia(4,3)+alph.*(((-1)+psix.*sig).*ia(3,3) ...
  +gam.*((-1)+psix.*sig).*ia(4,3)+kapp.*sig.*((-1).*ib(1,3)+ib(2,3)) ...
  )),alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  gam.*((-1)+psix.*sig).*(1+((-1)+alph).*ia(4,4))+alph.*(((-1)+ ...
  psix.*sig).*ia(3,4)+kapp.*sig.*((-1).*ib(1,4)+ib(2,4))));alph.^( ...
  -1).*sig.*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*((-1).* ...
  gam.*psipi.*ia(4,1)+alph.*(psipi.*(ia(3,1)+gam.*ia(4,1))+(-1).*ib( ...
  1,1)+ib(2,1))),alph.^(-1).*sig.*((-1)+(-1).*kapp.*psipi.*sig+ ...
  psix.*sig).^(-1).*((-1).*gam.*psipi.*ia(4,2)+alph.*(psipi.*(ia(3, ...
  2)+gam.*ia(4,2))+(-1).*ib(1,2)+ib(2,2))),alph.^(-1).*sig.*((-1)+( ...
  -1).*kapp.*psipi.*sig+psix.*sig).^(-1).*((-1).*gam.*psipi.*ia(4,3) ...
  +alph.*(psipi.*(ia(3,3)+gam.*ia(4,3))+(-1).*ib(1,3)+ib(2,3))), ...
  alph.^(-1).*sig.*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  gam.*psipi.*(1+((-1)+alph).*ia(4,4))+alph.*(psipi.*ia(3,4)+(-1).* ...
  ib(1,4)+ib(2,4)));alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.* ...
  sig).^(-1).*(gam.*psipi.*(1+(-2).*psix.*sig).*ia(4,1)+alph.*psix.* ...
  sig.*((-1).*ib(1,1)+ib(2,1))+alph.*psipi.*(((-1)+2.*psix.*sig).* ...
  ia(3,1)+gam.*((-1)+2.*psix.*sig).*ia(4,1)+kapp.*sig.*((-1).*ib(1, ...
  1)+ib(2,1)))),alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig) ...
  .^(-1).*(gam.*psipi.*(1+(-2).*psix.*sig).*ia(4,2)+alph.*((-1)+(-1) ...
  .*psipi.*(ia(3,2)+gam.*ia(4,2)+kapp.*sig.*(1+ib(1,2)+(-1).*ib(2,2) ...
  ))+psix.*sig.*(1+2.*psipi.*(ia(3,2)+gam.*ia(4,2))+(-1).*ib(1,2)+ ...
  ib(2,2)))),alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^( ...
  -1).*(gam.*psipi.*(1+(-2).*psix.*sig).*ia(4,3)+alph.*psix.*sig.*(( ...
  -1).*ib(1,3)+ib(2,3))+alph.*psipi.*(((-1)+2.*psix.*sig).*ia(3,3)+ ...
  gam.*((-1)+2.*psix.*sig).*ia(4,3)+kapp.*sig.*((-1).*ib(1,3)+ib(2, ...
  3)))),alph.^(-1).*((-1)+(-1).*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  gam.*psipi.*((-1)+2.*psix.*sig).*(1+((-1)+alph).*ia(4,4))+alph.*( ...
  psipi.*((-1)+2.*psix.*sig).*ia(3,4)+kapp.*psipi.*sig.*((-1).*ib(1, ...
  4)+ib(2,4))+psix.*sig.*((-1).*ib(1,4)+ib(2,4))))];

mathematica_code = "/Users/lauragati/Dropbox/BC_Research/next/code/materials13indexation_myopic.nb";
this_code = mfilename;
mname = strrep(this_code,'matrices_A_','')
mmcaname = extractBetween(mathematica_code,"/Users/lauragati/Dropbox/BC_Research/next/code/materials",".nb")

if strcmp(mname,mmcaname) ~=1
    error('not using the correct A-matrices from Mathematica!')
end