function [Aa, Ab, As] = matrices_A_13indexation_opt(param,hx)
% Mathematica, materials13indexation_opt.nb
% 17 jan 2020
% A-matrices for baseline model w/ indexation in NKPC, optimal forecasters info ass.

bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
gam = param.gam;
nx= size(hx,1); 

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% The only thing you need to specify by hand is 
ia = (eye(nx)-alph*bet*hx)^(-1);
ib = (eye(nx)-bet*hx)^(-1);

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [0,alph.^2.*bet.^2.*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1).*( ...
  kapp+kapp.*psix.*sig),0;0,(-1).*alph.^2.*bet.*kapp.*sig.*(bet+ ...
  alph.*kapp.*sig+bet.*psix.*sig).^(-1),0;0,alph.^2.*bet.*kapp.*( ...
  bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1).*(bet.*psipi+((-1)+bet.* ...
  psipi).*psix.*sig),0];
Ab = [0,(-1).*alph.*bet.*kapp.*((-1)+bet+bet.*psix.*sig).*(bet+alph.* ...
  kapp.*sig+bet.*psix.*sig).^(-1),0;0,(-1).*bet.*((-1)+bet+bet.* ...
  psix.*sig).*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1),0;0,(-1).* ...
  bet.*(alph.*kapp.*psipi+psix).*((-1)+bet+bet.*psix.*sig).*(bet+ ...
  alph.*kapp.*sig+bet.*psix.*sig).^(-1),0];

As = [alph.^(-1).*bet.^(-1).*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1) ...
  .*(bet.*((1+psix.*sig).*ia(4,1)+(-1).*alph.*(1+bet.*gam).*(1+ ...
  psix.*sig).*ia(4,1)+alph.^2.*bet.*((1+psix.*sig).*ia(3,1)+gam.*(1+ ...
  psix.*sig).*ia(4,1)+kapp.*sig.*(ib(1,1)+(-1).*ib(2,1))))+alph.^2.* ...
  kapp.*(1+(-1).*bet.*psipi).*sig.*ib(4,1)),alph.^(-1).*bet.^(-1).*( ...
  bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1).*(bet.*((1+psix.*sig).* ...
  ia(4,2)+(-1).*alph.*(1+bet.*gam).*(1+psix.*sig).*ia(4,2)+alph.^2.* ...
  bet.*((1+psix.*sig).*ia(3,2)+gam.*(1+psix.*sig).*ia(4,2)+kapp.* ...
  sig.*(ib(1,2)+(-1).*ib(2,2))))+alph.^2.*kapp.*(1+(-1).*bet.*psipi) ...
  .*sig.*ib(4,2)),alph.^(-1).*bet.^(-1).*(bet+alph.*kapp.*sig+bet.* ...
  psix.*sig).^(-1).*(bet.*((1+psix.*sig).*ia(4,3)+(-1).*alph.*(1+ ...
  bet.*gam).*(1+psix.*sig).*ia(4,3)+alph.^2.*bet.*((1+psix.*sig).* ...
  ia(3,3)+gam.*(1+psix.*sig).*ia(4,3)+kapp.*sig.*(ib(1,3)+(-1).*ib( ...
  2,3))))+alph.^2.*kapp.*(1+(-1).*bet.*psipi).*sig.*ib(4,3)),alph.^( ...
  -1).*bet.^(-1).*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1).*( ...
  alph.*bet.^2.*(gam.*(1+psix.*sig).*(1+((-1)+alph).*ia(4,4))+alph.* ...
  ((1+psix.*sig).*ia(3,4)+kapp.*sig.*(ib(1,4)+(-1).*ib(2,4))))+bet.* ...
  ((1+psix.*sig).*((-1)+ia(4,4))+(-1).*alph.*(1+psix.*sig).*((-1)+ ...
  ia(4,4))+(-1).*alph.^2.*kapp.*psipi.*sig.*((-1)+ib(4,4)))+ ...
  alph.^2.*kapp.*sig.*((-1)+ib(4,4)));(-1).*alph.^(-1).*bet.^(-1).* ...
  sig.*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1).*(ia(4,1)+alph.*(( ...
  -1).*(1+bet.*gam).*ia(4,1)+alph.*bet.*(ia(3,1)+gam.*ia(4,1))+ ...
  bet.^2.*((-1).*ib(1,1)+ib(2,1))+((-1)+bet.*psipi).*ib(4,1))),(-1) ...
  .*alph.^(-1).*bet.^(-1).*sig.*(bet+alph.*kapp.*sig+bet.*psix.*sig) ...
  .^(-1).*(ia(4,2)+alph.*((-1).*(1+bet.*gam).*ia(4,2)+alph.*bet.*( ...
  ia(3,2)+gam.*ia(4,2))+bet.^2.*((-1).*ib(1,2)+ib(2,2))+((-1)+bet.* ...
  psipi).*ib(4,2))),(-1).*alph.^(-1).*bet.^(-1).*sig.*(bet+alph.* ...
  kapp.*sig+bet.*psix.*sig).^(-1).*(ia(4,3)+alph.*((-1).*(1+bet.* ...
  gam).*ia(4,3)+alph.*bet.*(ia(3,3)+gam.*ia(4,3))+bet.^2.*((-1).*ib( ...
  1,3)+ib(2,3))+((-1)+bet.*psipi).*ib(4,3))),(-1).*alph.^(-1).* ...
  bet.^(-1).*sig.*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1).*((-1)+ ...
  ia(4,4)+alph.*(2+(-1).*ia(4,4)+bet.*(gam+alph.*ia(3,4)+((-1)+alph) ...
  .*gam.*ia(4,4)+(-1).*bet.*ib(1,4)+bet.*ib(2,4)+psipi.*((-1)+ib(4, ...
  4)))+(-1).*ib(4,4)));alph.^(-1).*bet.^(-1).*(bet+alph.*kapp.*sig+ ...
  bet.*psix.*sig).^(-1).*((bet.*psipi+((-1)+bet.*psipi).*psix.*sig) ...
  .*ia(4,1)+alph.^2.*(bet.*(((-1)+bet.*psipi).*psix.*sig.*(ia(3,1)+ ...
  gam.*ia(4,1))+bet.*psipi.*(ia(3,1)+gam.*ia(4,1)+kapp.*sig.*(ib(1, ...
  1)+(-1).*ib(2,1))))+kapp.*psipi.*(1+(-1).*bet.*psipi).*sig.*ib(4, ...
  1))+(-1).*alph.*(bet.*(1+bet.*gam).*psipi.*ia(4,1)+psix.*sig.*((1+ ...
  bet.*gam).*((-1)+bet.*psipi).*ia(4,1)+bet.^2.*((-1).*ib(1,1)+ib(2, ...
  1))+((-1)+bet.*psipi).*ib(4,1)))),alph.^(-1).*bet.^(-1).*(bet+ ...
  alph.*kapp.*sig+bet.*psix.*sig).^(-1).*((bet.*psipi+((-1)+bet.* ...
  psipi).*psix.*sig).*ia(4,2)+alph.^2.*(bet.*(bet.*psipi+((-1)+bet.* ...
  psipi).*psix.*sig).*(ia(3,2)+gam.*ia(4,2))+bet.*kapp.*sig.*(1+ ...
  bet.*psipi.*(ib(1,2)+(-1).*ib(2,2)))+kapp.*psipi.*(1+(-1).*bet.* ...
  psipi).*sig.*ib(4,2))+alph.*(bet.*(gam.*psix.*sig+(-1).*psipi.*(1+ ...
  psix.*sig)).*ia(4,2)+bet.^2.*(1+(-1).*gam.*psipi.*ia(4,2)+psix.* ...
  sig.*(1+(-1).*gam.*psipi.*ia(4,2)+ib(1,2)+(-1).*ib(2,2)))+(-1).* ...
  bet.*psipi.*psix.*sig.*ib(4,2)+psix.*sig.*(ia(4,2)+ib(4,2)))), ...
  alph.^(-1).*bet.^(-1).*(bet+alph.*kapp.*sig+bet.*psix.*sig).^(-1) ...
  .*((bet.*psipi+((-1)+bet.*psipi).*psix.*sig).*ia(4,3)+alph.^2.*( ...
  bet.*(((-1)+bet.*psipi).*psix.*sig.*(ia(3,3)+gam.*ia(4,3))+bet.* ...
  psipi.*(ia(3,3)+gam.*ia(4,3)+kapp.*sig.*(ib(1,3)+(-1).*ib(2,3))))+ ...
  kapp.*psipi.*(1+(-1).*bet.*psipi).*sig.*ib(4,3))+(-1).*alph.*( ...
  bet.*(1+bet.*gam).*psipi.*ia(4,3)+psix.*sig.*((1+bet.*gam).*((-1)+ ...
  bet.*psipi).*ia(4,3)+bet.^2.*((-1).*ib(1,3)+ib(2,3))+((-1)+bet.* ...
  psipi).*ib(4,3)))),alph.^(-1).*bet.^(-1).*(bet+alph.*kapp.*sig+ ...
  bet.*psix.*sig).^(-1).*(psipi.*(alph.*bet.^2.*(gam+((-1)+alph).* ...
  gam.*ia(4,4)+alph.*(ia(3,4)+kapp.*sig.*(ib(1,4)+(-1).*ib(2,4))))+ ...
  bet.*((-1)+ia(4,4)+(-1).*alph.*((-1)+ia(4,4)+alph.*kapp.*psipi.* ...
  sig.*((-1)+ib(4,4))))+alph.^2.*kapp.*sig.*((-1)+ib(4,4)))+psix.* ...
  sig.*(((-1)+bet.*psipi).*((-1)+ia(4,4))+alph.^2.*bet.*((-1)+bet.* ...
  psipi).*(ia(3,4)+gam.*ia(4,4))+alph.*((-2)+ia(4,4)+ib(4,4)+(-1).* ...
  bet.*(gam.*((-1)+bet.*psipi).*((-1)+ia(4,4))+bet.*((-1).*ib(1,4)+ ...
  ib(2,4))+psipi.*((-2)+ia(4,4)+ib(4,4))))))];

mathematica_code = "/Users/lauragati/Dropbox/BC_Research/next/code/materials13indexation_opt.nb";
this_code = mfilename;
mname = strrep(this_code,'matrices_A_','')
mmcaname = extractBetween(mathematica_code,"/Users/lauragati/Dropbox/BC_Research/next/code/materials",".nb")

if strcmp(mname,mmcaname) ~=1
    error('not using the correct A-matrices from Mathematica!')
end