function [Aa, Ab, As] = matrices_A_13_pill_subopt_fcst(param,hx)
% Mathematica, materials13_pill_subopt_fcst.nb
% 19 jan 2020
% A-matrices for the pill extension, "suboptimal forecasters" info ass.

bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
gam = param.gam;
nx= size(hx,1); 

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% The only thing you need to specify by hand is 
ia = (eye(nx)-alph*bet*hx)^(-1);
ib = (eye(nx)-bet*hx)^(-1);

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [(-1).*((-1)+alph).*bet.*(1+psix.*sig).*(1+bet.^2.*kapp.*psipi.* ...
  sig+psix.*sig).^(-1),alph.*bet.*kapp.*(1+psix.*sig).*(1+bet.^2.* ...
  kapp.*psipi.*sig+psix.*sig).^(-1),0;((-1)+alph).*bet.^3.*psipi.* ...
  sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*alph.* ...
  bet.^3.*kapp.*psipi.*sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig) ...
  .^(-1),0;((-1)+alph).*bet.^3.*psipi.*psix.*sig.*(1+bet.^2.*kapp.* ...
  psipi.*sig+psix.*sig).^(-1),(-1).*alph.*bet.^3.*kapp.*psipi.* ...
  psix.*sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1),0];
Ab = [kapp.*(1+(-1).*bet.^3.*psipi).*sig.*(1+bet.^2.*kapp.*psipi.*sig+ ...
  psix.*sig).^(-1),(-1).*kapp.*(1+bet.^2.*kapp.*psipi.*sig+psix.* ...
  sig).^(-1).*((-1)+bet+bet.*psix.*sig),0;(sig+(-1).*bet.^3.*psipi.* ...
  sig).*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*(1+ ...
  bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*((-1)+bet+bet.*psix.* ...
  sig),0;(1+(-1).*bet.^3.*psipi).*psix.*sig.*(1+bet.^2.*kapp.* ...
  psipi.*sig+psix.*sig).^(-1),(-1).*psix.*(1+bet.^2.*kapp.*psipi.* ...
  sig+psix.*sig).^(-1).*((-1)+bet+bet.*psix.*sig),0];
As = [(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*((1+psix.*sig).*ia( ...
  3,1)+kapp.*sig.*(ib(1,1)+(-1).*ib(2,1))),(1+bet.^2.*kapp.*psipi.* ...
  sig+psix.*sig).^(-1).*((1+psix.*sig).*ia(3,2)+kapp.*sig.*(ib(1,2)+ ...
  (-1).*ib(2,2))),(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*((1+ ...
  psix.*sig).*ia(3,3)+kapp.*sig.*(ib(1,3)+(-1).*ib(2,3))),(1+ ...
  bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*(ia(3,4)+psix.*sig.*ia( ...
  3,4)+(-1).*kapp.*sig.*(bet.*psipi+(-1).*ib(1,4)+ib(2,4))),(1+ ...
  bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*((1+psix.*sig).*ia(3,5) ...
  +(-1).*kapp.*sig.*(psipi+(-1).*ib(1,5)+ib(2,5)));(-1).*sig.*(1+ ...
  bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*(bet.^2.*psipi.*ia(3,1) ...
  +(-1).*ib(1,1)+ib(2,1)),(-1).*sig.*(1+bet.^2.*kapp.*psipi.*sig+ ...
  psix.*sig).^(-1).*(bet.^2.*psipi.*ia(3,2)+(-1).*ib(1,2)+ib(2,2)),( ...
  -1).*sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*(bet.^2.* ...
  psipi.*ia(3,3)+(-1).*ib(1,3)+ib(2,3)),(-1).*sig.*(1+bet.^2.*kapp.* ...
  psipi.*sig+psix.*sig).^(-1).*(bet.*psipi.*(1+bet.*ia(3,4))+(-1).* ...
  ib(1,4)+ib(2,4)),(-1).*sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig) ...
  .^(-1).*(psipi+bet.^2.*psipi.*ia(3,5)+(-1).*ib(1,5)+ib(2,5));(-1) ...
  .*psix.*sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  bet.^2.*psipi.*ia(3,1)+(-1).*ib(1,1)+ib(2,1)),(1+bet.^2.*kapp.* ...
  psipi.*sig+psix.*sig).^(-1).*(1+bet.^2.*kapp.*psipi.*sig+psix.* ...
  sig.*(1+(-1).*bet.^2.*psipi.*ia(3,2)+ib(1,2)+(-1).*ib(2,2))),(-1) ...
  .*psix.*sig.*(1+bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  bet.^2.*psipi.*ia(3,3)+(-1).*ib(1,3)+ib(2,3)),(-1).*psix.*sig.*(1+ ...
  bet.^2.*kapp.*psipi.*sig+psix.*sig).^(-1).*(bet.*psipi.*(1+bet.* ...
  ia(3,4))+(-1).*ib(1,4)+ib(2,4)),(1+bet.^2.*kapp.*psipi.*sig+psix.* ...
  sig).^(-1).*(psipi+bet.^2.*kapp.*psipi.^2.*sig+(-1).*bet.^2.* ...
  psipi.*psix.*sig.*ia(3,5)+psix.*sig.*(ib(1,5)+(-1).*ib(2,5)))];

mathematica_code = "/Users/lauragati/Dropbox/BC_Research/next/code/materials13_pill_subopt_fcst.nb";
this_code = mfilename;
mname = strrep(this_code,'matrices_A_','')
mmcaname = extractBetween(mathematica_code,"/Users/lauragati/Dropbox/BC_Research/next/code/materials",".nb")

if strcmp(mname,mmcaname) ~=1
    error('not using the correct A-matrices from Mathematica!')
end