function [Aa, Ab, As] = matrices_A_12i(param,hx)
% Mathematica, materials12i.nb
% 14 jan 2020
% A-matrices for baseline model w/o agents knowing the Taylor-rule.

bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
nx= size(hx,1); % need to figure this out later

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% The only thing you need to specify by hand is 
ia = (eye(nx)-alph*bet*hx)^(-1);
ib = (eye(nx)-bet*hx)^(-1);

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [(-1).*((-1)+alph).*bet.*(1+psix.*sig).*(1+kapp.*psipi.*sig+psix.* ...
  sig).^(-1),alph.*bet.*kapp.*(1+psix.*sig).*(1+kapp.*psipi.*sig+ ...
  psix.*sig).^(-1),0;((-1)+alph).*bet.*psipi.*sig.*(1+kapp.*psipi.* ...
  sig+psix.*sig).^(-1),(-1).*alph.*bet.*kapp.*psipi.*sig.*(1+kapp.* ...
  psipi.*sig+psix.*sig).^(-1),0;(-1).*((-1)+alph).*bet.*psipi.*(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1),alph.*bet.*kapp.*psipi.*(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1),0];
Ab = [kapp.*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1),(kapp+(-1).*bet.* ...
  kapp).*(1+kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*bet.*kapp.*sig.* ...
  (1+kapp.*psipi.*sig+psix.*sig).^(-1);sig.*(1+kapp.*psipi.*sig+ ...
  psix.*sig).^(-1),(1+(-1).*bet).*(1+kapp.*psipi.*sig+psix.*sig).^( ...
  -1),(-1).*bet.*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1);1+(-1).*( ...
  1+kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*((-1)+bet).*(kapp.* ...
  psipi+psix).*(1+kapp.*psipi.*sig+psix.*sig).^(-1),bet.*((-1)+(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1))];
As = [(1+kapp.*psipi.*sig+psix.*sig).^(-1).*(ia(3,1)+psix.*sig.*ia(3,1) ...
  +kapp.*sig.*ib(1,1)),(1+kapp.*psipi.*sig+psix.*sig).^(-1).*((1+ ...
  psix.*sig).*ia(3,2)+kapp.*sig.*((-1)+ib(1,2))),(1+kapp.*psipi.* ...
  sig+psix.*sig).^(-1).*(ia(3,3)+psix.*sig.*ia(3,3)+kapp.*sig.*ib(1, ...
  3));sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1).*((-1).*psipi.*ia(3, ...
  1)+ib(1,1)),sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1).*((-1)+(-1) ...
  .*psipi.*ia(3,2)+ib(1,2)),sig.*(1+kapp.*psipi.*sig+psix.*sig).^( ...
  -1).*((-1).*psipi.*ia(3,3)+ib(1,3));(1+kapp.*psipi.*sig+psix.*sig) ...
  .^(-1).*(psipi.*ia(3,1)+(kapp.*psipi+psix).*sig.*ib(1,1)),(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1).*(1+psipi.*ia(3,2)+(kapp.*psipi+ ...
  psix).*sig.*ib(1,2)),(1+kapp.*psipi.*sig+psix.*sig).^(-1).*( ...
  psipi.*ia(3,3)+(kapp.*psipi+psix).*sig.*ib(1,3))];

mathematica_code = "/Users/lauragati/Dropbox/BC_Research/next/code/materials12i.nb";
this_code = mfilename;
mname = strrep(this_code,'matrices_A_','')
mmcaname = extractBetween(mathematica_code,"/Users/lauragati/Dropbox/BC_Research/next/code/materials",".nb")

if strcmp(mname,mmcaname) ~=1
    error('not using the correct A-matrices from Mathematica!')
end