function [Aa, Ab, As] = matrices_A_12g3(param,hx)
% Mathematica, materials12g3.nb
% 9 jan 2020
% A-matrices for il-model, with "optimal forecaster" info assumption.
bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
nx= size(hx,1); % need to figure this out later

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% The only thing you need to specify by hand is 
ia = (eye(nx)-alph*bet*hx)^(-1);
ib = (eye(nx)-bet*hx)^(-1);

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [(-1).*((-1)+alph).*bet.*((-1)+2.*psix.*sig).*((-1)+2.*(kapp.* ...
  psipi+psix).*sig).^(-1),alph.*bet.*kapp.*((-1)+2.*psix.*sig).*(( ...
  -1)+2.*(kapp.*psipi+psix).*sig).^(-1),0;2.*((-1)+alph).*bet.* ...
  psipi.*sig.*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1),(-2).*alph.* ...
  bet.*kapp.*psipi.*sig.*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1),0;( ...
  (-1)+alph).*bet.*psipi.*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1), ...
  alph.*bet.*kapp.*psipi.*(1+(-2).*(kapp.*psipi+psix).*sig).^(-1), ...
  0];
Ab = [kapp.*sig.*(1+(-2).*(kapp.*psipi+psix).*sig).^(-1),((-1)+bet).* ...
  kapp.*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1),0;sig.*(1+(-2).*( ...
  kapp.*psipi+psix).*sig).^(-1),((-1)+bet).*((-1)+2.*(kapp.*psipi+ ...
  psix).*sig).^(-1),0;(-1).*(kapp.*psipi+psix).*sig.*((-1)+2.*( ...
  kapp.*psipi+psix).*sig).^(-1),((-1)+bet).*(kapp.*psipi+psix).*(( ...
  -1)+2.*(kapp.*psipi+psix).*sig).^(-1),0];
As = [bet.^(-1).*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1).*(bet.*((-1)+ ...
  2.*psix.*sig).*ia(3,1)+(-1).*bet.*kapp.*sig.*ib(1,1)+kapp.*sig.* ...
  ib(4,1)),bet.^(-1).*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1).*((-1) ...
  .*bet.*((1+(-2).*psix.*sig).*ia(3,2)+kapp.*sig.*(2+ib(1,2)))+ ...
  kapp.*sig.*ib(4,2)),bet.^(-1).*((-1)+2.*(kapp.*psipi+psix).*sig) ...
  .^(-1).*(bet.*((-1)+2.*psix.*sig).*ia(3,3)+(-1).*bet.*kapp.*sig.* ...
  ib(1,3)+kapp.*sig.*ib(4,3)),bet.^(-1).*((-1)+2.*(kapp.*psipi+psix) ...
  .*sig).^(-1).*(bet.*((-1)+2.*psix.*sig).*ia(3,4)+kapp.*sig.*((-1)+ ...
  (-1).*bet.*(2.*rho+ib(1,4))+ib(4,4)));bet.^(-1).*sig.*((-1)+2.*( ...
  kapp.*psipi+psix).*sig).^(-1).*((-1).*bet.*(2.*psipi.*ia(3,1)+ib( ...
  1,1))+ib(4,1)),bet.^(-1).*sig.*((-1)+2.*(kapp.*psipi+psix).*sig) ...
  .^(-1).*((-1).*bet.*(2+2.*psipi.*ia(3,2)+ib(1,2))+ib(4,2)),bet.^( ...
  -1).*sig.*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1).*((-1).*bet.*( ...
  2.*psipi.*ia(3,3)+ib(1,3))+ib(4,3)),sig.*(bet+(-2).*bet.*(kapp.* ...
  psipi+psix).*sig).^(-1).*(1+bet.*(2.*rho+2.*psipi.*ia(3,4)+ib(1,4) ...
  )+(-1).*ib(4,4));bet.^(-1).*((-1)+2.*(kapp.*psipi+psix).*sig).^( ...
  -1).*((-1).*bet.*psipi.*ia(3,1)+(-1).*bet.*(kapp.*psipi+psix).* ...
  sig.*ib(1,1)+(kapp.*psipi+psix).*sig.*ib(4,1)),bet.^(-1).*((-1)+ ...
  2.*(kapp.*psipi+psix).*sig).^(-1).*((-1).*bet.*(1+psipi.*ia(3,2)+( ...
  kapp.*psipi+psix).*sig.*ib(1,2))+(kapp.*psipi+psix).*sig.*ib(4,2)) ...
  ,bet.^(-1).*((-1)+2.*(kapp.*psipi+psix).*sig).^(-1).*((-1).*bet.* ...
  psipi.*ia(3,3)+(-1).*bet.*(kapp.*psipi+psix).*sig.*ib(1,3)+(kapp.* ...
  psipi+psix).*sig.*ib(4,3)),bet.^(-1).*((-1)+2.*(kapp.*psipi+psix) ...
  .*sig).^(-1).*((-1).*bet.*(rho+psipi.*ia(3,4)+(kapp.*psipi+psix).* ...
  sig.*ib(1,4))+(kapp.*psipi+psix).*sig.*((-1)+ib(4,4)))];
  