function [Aa, Ab, As, Ba, Bb] = matrices_A_13_learnhx_baseline(param,hx)
% Mathematica, materials13_learnhx_baseline.nb
% 18 jan 2020
% A-matrices for learning hx, baseline model.

bet = param.bet;  
sig = param.sig;
alph = param.alph;
kapp = param.kapp;
psi_x = param.psi_x;
psi_pi = param.psi_pi;
w = param.w;
gbar = param.gbar;
thetbar = param.thetbar;
rho_r = param.rho_r;
rho_i = param.rho_i;
rho_u = param.rho_u;
sig_r = param.sig_r;
sig_i = param.sig_i;
sig_u = param.sig_u;
rho = param.rho;
gam = param.gam;
nx= size(hx,1); 

% transform these two to be compatible with Mathematica
psipi = psi_pi;
psix = psi_x;

% Given the d-matrices, the solution is calculated in Mathematica and
% copied from there:
Aa = [(-1).*((-1)+alph).*bet.*(1+psix.*sig).*(1+kapp.*psipi.*sig+psix.* ...
  sig).^(-1),alph.*bet.*kapp.*(1+psix.*sig).*(1+kapp.*psipi.*sig+ ...
  psix.*sig).^(-1),0;((-1)+alph).*bet.*psipi.*sig.*(1+kapp.*psipi.* ...
  sig+psix.*sig).^(-1),(-1).*alph.*bet.*kapp.*psipi.*sig.*(1+kapp.* ...
  psipi.*sig+psix.*sig).^(-1),0;(-1).*((-1)+alph).*bet.*psipi.*(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1),alph.*bet.*kapp.*psipi.*(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1),0];
Ab = [kapp.*(1+(-1).*bet.*psipi).*sig.*(1+kapp.*psipi.*sig+psix.*sig) ...
  .^(-1),(-1).*kapp.*(1+kapp.*psipi.*sig+psix.*sig).^(-1).*((-1)+ ...
  bet+bet.*psix.*sig),0;(sig+(-1).*bet.*psipi.*sig).*(1+kapp.* ...
  psipi.*sig+psix.*sig).^(-1),(-1).*(1+kapp.*psipi.*sig+psix.*sig) ...
  .^(-1).*((-1)+bet+bet.*psix.*sig),0;(-1).*((-1)+bet.*psipi).*( ...
  kapp.*psipi+psix).*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1),(-1) ...
  .*(kapp.*psipi+psix).*(1+kapp.*psipi.*sig+psix.*sig).^(-1).*((-1)+ ...
  bet+bet.*psix.*sig),0];

As = [kapp.*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*kapp.*sig.* ...
  (1+kapp.*psipi.*sig+psix.*sig).^(-1),(1+psix.*sig).*(1+kapp.* ...
  psipi.*sig+psix.*sig).^(-1);sig.*(1+kapp.*psipi.*sig+psix.*sig).^( ...
  -1),(-1).*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*psipi.* ...
  sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1);1+(-1).*(1+kapp.*psipi.* ...
  sig+psix.*sig).^(-1),(1+kapp.*psipi.*sig+psix.*sig).^(-1),psipi.*( ...
  1+kapp.*psipi.*sig+psix.*sig).^(-1)];
Ba = [0,0,alph.*bet.*(1+psix.*sig).*(1+kapp.*psipi.*sig+psix.*sig).^( ...
  -1);0,0,(-1).*alph.*bet.*psipi.*sig.*(1+kapp.*psipi.*sig+psix.* ...
  sig).^(-1);0,0,alph.*bet.*psipi.*(1+kapp.*psipi.*sig+psix.*sig).^( ...
  -1)];
Bb = [bet.*kapp.*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*bet.* ...
  kapp.*sig.*(1+kapp.*psipi.*sig+psix.*sig).^(-1),0;bet.*sig.*(1+ ...
  kapp.*psipi.*sig+psix.*sig).^(-1),(-1).*bet.*sig.*(1+kapp.*psipi.* ...
  sig+psix.*sig).^(-1),0;bet+(-1).*bet.*(1+kapp.*psipi.*sig+psix.* ...
  sig).^(-1),bet.*((-1)+(1+kapp.*psipi.*sig+psix.*sig).^(-1)),0];

mathematica_code = "/Users/lauragati/Dropbox/BC_Research/next/code/materials13_learnhx_baseline.nb";
this_code = mfilename;
mname = strrep(this_code,'matrices_A_','')
mmcaname = extractBetween(mathematica_code,"/Users/lauragati/Dropbox/BC_Research/next/code/materials",".nb")

if strcmp(mname,mmcaname) ~=1
    error('not using the correct A-matrices from Mathematica!')
end